name: Create envfile

on: [ push ]

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_EE_KEY: ${{ secrets.EE_KEY }}
        directory: ./
        file_name: .env
        fail_on_empty: false
        sort_keys: false